### ISSUE TITLE
getting "java.lang.IllegalStateException: Already managing a GoogleApiClient with id 0" when activity resumes

### ISSUE THREAD

**Issue by Alfishan** [RogaLabs/social-login#1]
`08-01 16:48:02.451 20917-20917/com.xeme.motolift_messenger E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.xeme.motolift_messenger, PID: 20917
                                                                             java.lang.RuntimeException: Unable to resume activity {com.xeme.motolift_messenger/com.xeme.motolift_messenger.ui.activity.MainActivity}: java.lang.IllegalStateException: Already managing a GoogleApiClient with id 0
                                                                                 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2986)
                                                                                 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                              Caused by: java.lang.IllegalStateException: Already managing a GoogleApiClient with id 0
                                                                                 at com.google.android.gms.common.internal.zzaa.zza(Unknown Source)
                                                                                 at com.google.android.gms.internal.zznr.zza(Unknown Source)
                                                                                 at com.google.android.gms.common.api.GoogleApiClient$Builder.zze(Unknown Source)
                                                                                 at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
                                                                                 at com.rogalabs.lib.google.LoginGooglePresenter.start(LoginGooglePresenter.kt:32)
                                                                                 at com.rogalabs.lib.LoginView.onStart(LoginView.kt:39)
                                                                                 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
                                                                                 at android.app.Activity.performStart(Activity.java:6006)
                                                                                 at android.app.Activity.performRestart(Activity.java:6063)
                                                                                 at android.app.Activity.performResume(Activity.java:6068)
                                                                                 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
                                                                                 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
08-01 16:53:02.483 20917-20917/com.xeme.motolift_messenger I/Process: Sending signal. PID: 20917 SIG: 9
`

fb and g+ login work like charm but it  crash when activity resumes. 
i tried every thing from my side. also tested my code in different devices. let me know if there are any bugs. thanks you are doing good ... keep up da good work..

**Comment by oliveiradev** [comment]
Hey @Alfishan4 , thanks for report, I will go look this

**Comment by Alfishan** [comment]
you are welcome. I think its related to " mGoogleApiClient?.stopAutoManage(this.activity!!)". you are calling this at onDestroy(). i thing it should be at onStop(). (i think so :) ).

**Comment by cleylsonsouza** [comment]
Fixed on branch **develop**.

**Comment by patelanil2007** [comment]
how to get latest lib? @cleylsonsouza

**Comment by cjxonix** [comment]
Even me am getting the same issue

**Comment by cjxonix** [comment]
But the Lib is totally great and simple to use... Once we remove this bug

**Comment by ayush18verma** [comment]
@cjxonix Did you solve this error? i have the same problem , i commented to this issue long before but he didn't reply and rectify it!!!

**Comment by ayush18verma** [comment]
@cjxonix Update your  project build.gradle with:
compile 'com.github.RogaLabs:social-login:0.3.1'
