### ISSUE TITLE
Facebook onclick error

### ISSUE THREAD

**Issue by Naguchennai** [RogaLabs/social-login#9]
Facebook button onclick this errror
its only happen with compile 'com.google.android.exoplayer:exoplayer:r2.3.1'
update your sample with new vertion

` Log in attempt failed: LoginActivity could not be started
                                                       at com.facebook.login.LoginManager.startLogin(LoginManager.java:382)
                                                       at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:262)
                                                       at com.rogalabs.lib.facebook.LoginFacebookPresenter.signIn(LoginFacebookPresenter.kt:61)
                                                       at com.rogalabs.lib.LoginView.loginWithFacebook(LoginView.kt:81)`

**Comment by mrajunda** [comment]
same here
